### ISSUE TITLE
Some requests have active "Fund this project" and "Submit solution" buttons and some have disabled ones - what is the reason? (question, maybe a bug)

### ISSUE THREAD

**Issue by rustam-snet** [singnet/snet-rfai-dapp#27]
**Testing Environment:**

Windows 10, Google Chrome 73.0.3683.86 (64bit), 15.6", 1920х1080

**Steps to reproduce:**

1. Navigate to http://rfai.singularitynet.io.s3-website-us-east-1.amazonaws.com/
2. Scroll down to the "Sample Request Title" request
3. Expand the info about this request
4. Observe the state of all buttons
5. Expand the info about "Object detection in a real time video stream" request
6. Observe the state of all buttons
7. Expand the info about "Language Translation Services" request
8. Observe the state of all buttons

**EXPECTED RESULT:**

I expected that state of "View solution", "Fund this project" and "Submit solution" buttons will be the same for all requests

**ACTUAL RESULT:**

Somehow "Fund this project" and "Submit solution" buttons are disabled for "Object detection in a real time video stream" and "Language Translation Services" requests and I don't understand the reason.

**Please see the video below**

![20190405_07h47_17](https://user-images.githubusercontent.com/12077703/55604164-2a111c80-5777-11e9-82c8-f79395b9a343.gif)

**Comment by ksridharbabuus** [comment]
This is as per the functionality and it varies based on the state of the Request and the current phase of the request it is in.

Looks like there is no issue here.

**Comment by smbss** [comment]
Hi @ksridharbabuus , when you mention "state of the request" you mean if it is expired or not, correct? 
I think that the first service on the active list is supposed to not be expired, while the remaining ones should be expired since it is not possible to fund them anymore right? 
The problem is that the expired dates are all in the future, and I believe this is what caused a misinterpretation to @rustam-snet , because it should indicate that all requests are not expired yet - so I was just trying to understand if I got this right and this is just a mockup mistake on the expired dates, or if it can have something related to the logic between the expired date and the status itself.
